import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import '../style/globals.css'
import Header from "../components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ['latin'], 
  weight: ['400', '600', '700'], 
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Shopping website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
